services:

    _defaults:
        autowire: true
        autoconfigure: true

    # tool installer
    LuceneSearchBundle\Tool\Install:
        public: true
        
    # configuration
    LuceneSearchBundle\Configuration\Configuration: ~

    # tool crawler state
    LuceneSearchBundle\Tool\CrawlerState:
        public: true

    LuceneSearchBundle\EventListener\PimcoreAdminListener:
        tags:
            #- { name: kernel.event_listener, event: pimcore.bundle_manager.paths.css, method: addCSSFiles }
            - { name: kernel.event_listener, event: pimcore.bundle_manager.paths.js, method: addJSFiles }